PROJECT PLAN 
  VOTING SYSTEM  
   ABOUT 
   IT WILL SCAN THE VOTER ID CARD , AS IF THE ID CARD WILL SCAN, IT WILL SHOW THE CANDIATE'S THOSE WHO STOOD FOR ELECTION.
   GIVE YOUR VALUABLE VOTE AS YOU WANT TO GIVE PEOPLE.